# Generated by Django 2.2.5 on 2019-09-19 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='patios/servicios/')),
                ('horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de trabajo')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar en mi site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(upload_to='patios/images/')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar en site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patios.Pagina')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=13)),
                ('pueblo', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=150, verbose_name='Dirección')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='patios.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('posicion', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patios.Pagina')),
            ],
            options={
                'ordering': ['pagina', 'posicion'],
                'unique_together': {('pagina', 'posicion')},
            },
        ),
    ]
