# Generated by Django 2.2.5 on 2019-09-25 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='comentarios',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pueblo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
