# Generated by Django 2.2.5 on 2019-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patios', '0003_auto_20190926_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='horas',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Horas de trabajo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
